### ISSUE TITLE
json 파일을 뷰에 사용할 구조로 정제합니다

### ISSUE THREAD

**Issue by TaekH** [HipstuCAU/nyam_nyam#15]
### firestore에서 다운로드한 json 파일을 뷰에서 사용할 수 있도록 정제합니다.
정제한 함수들 `DataManager.swift`에 속하며 각 뷰의 `ViewModel` 에서 사용될 예정입니다.

<image width = 200  src = "https://user-images.githubusercontent.com/103012087/223156275-766a6bb8-f8c4-4942-81cf-2e05a3afc7ac.png">
불러온 json 파일은 위의 뷰와 #3 이슈의 모델에 따라서 정제될 예정입니다.

정제의 최종은 `getMealsForWeeks`를 구현하는 것이 목적입니다.
정제의 과정은 아래와 같습니다.
```swift
func jsonToString() -> String {
	//json파일을 string으로 변환합니다.
}

func stringToDict() -> [String: Any]? {
	if let strData = jsonToString() {
		//string을 dict로 변환합니다
	}
}

func getMealsForDay(_ campus: String) -> [Meal] {
	let dictData = stringToDict()
	if  let dayDict = dict?[campus] as? [String: Any],
	    let day = dayDict.keys.first,
	    let mealTimeDict = dayDict[day] as? [String: Any],
	    let mealTime = mealTimeDict.keys.first,
	    let cafeteriaDict = mealTimeDict[mealTime] as? [String: Any],
	    let cafeteria = cafeteriaDict.keys.first,
	    let mealTypeDict = cafeteriaDict[cafeteria] as? [String: Any],
	    let mealType = mealTypeDict.keys.first,
	    let menuDict = mealTypeDict[mealType] as? [String: Any],
	    let menu = menuDict["menu"] as? String,
	    let price = menuDict["price"] as? String {
	//Dict의 데이터를 Meal 모델에 맞춰서 [Meal] 배열을 생성합니다
}

func getMealsForWeeks(_ campus: String) -> [MealForDays] {
	days: [Date]= [오늘부터 7일치의 날짜]
	for days in day {
		//getMealsForDays(campus)의 Date와 비교하여 하루치 식단 배열이 Set<Meal> 안에 들어가고 
		//필요에 의해 date에 따라서 호출하시면 될 것 같습니다!
	}
}
```
변환된 String을 다시 Dictionary 형식으로 변환합니다.
Dictionary를 이용하여 Meal 모델에 맞추어 [Meal] 배열을 생성합니다.
이 Meal 배열 요소는 `하루 한 타임의 식당 안의 하나의 식단`이 될 예정입니다.

만들어진 Meal 배열은 다시 `getMealsForWeeks()` 함수 내에서 날짜에 따라서 [MealsForDay] 에 들어가 반환될 예정입니다!

추가적으로 json에서 인덱스로 들어온 데이터들을 정제하는 함수들도 따로 선언되지만 `getMealsForDay()` 내부에서 사용될 예정입니다.

사용될 정제 함수 예시는 아래와 같습니다.
```swift
func getMealTime(_ mealTime: String) -> String {
    let mealString
    switch mealTime {
        case "0":
            mealString = "조식"
        case "1":
	    mealString = "중식"
	case "2":
            mealString = "석식"
        default:
            mealString = " "
    }
}
```
@feldblume5263 `getMealsForWeeks()` 함수가 생각하신대로 구현되었는지 확인 후에 리뷰 부탁드립니다 !

**Comment by feldblume5263** [comment]
네 함께 논의한대로 잘 구성되어있는 것 같습니다.
저희가 백엔드가 없는 서러움이 코드에서 묻어나오는 것 같지만... 이렇게라도 가져올 수 있다면... 행복한걸...

**Comment by TaekH** [comment]
> 네 함께 논의한대로 잘 구성되어있는 것 같습니다.
> 저희가 백엔드가 없는 서러움이 코드에서 묻어나오는 것 같지만... 이렇게라도 가져올 수 있다면... 행복한걸...

😭 확인했습니다 !

**Comment by sy5072** [comment]
days in day -> day in days 오타인거죵...?
