### ISSUE TITLE
Json 형식 픽스 따른 Model 결정

### ISSUE THREAD

**Issue by feldblume5263** [HipstuCAU/nyam_nyam#3]
Model은 많이 복잡하지 않습니다.
크게 세개로 나뉘는데, **`Campus`**,  **`MealsForDay`**,  **`Meal`** 입니다.

<br>

먼저 요약을 하자면,
**`Meal`이 날짜별로 모여서 `MealsForDay`이 되고, `Campus`에서 선택한 캠퍼스별로 일주일치(7개)의 `MealsForDay`를 가져옵니다.**

<br>

`Meal` -> `MealsForDay` -> `Campus` 의 순서로 설명해드릴게요.

<br><br>

### 1. Meal

단일 Meal입니다.

``` swift
struct Meal: Hashable {
    let mealTime: MealTime
    let type: String
    let cafeteria: Cafeteria
    let price: String
    let menu: String
    let date: Date
}
```

`mealTime`은 조중석식을 나타내며 enum입니다.
`type`은 한식, 특식, 양식 같은 타입을 나타내지만, 현재는 디자이너와의 협의를 통해 빠질 가능성이 다분합니다...
`cafeteria`는 Cafeteria enum입니다. 장소를 나타냅니다.
`price`는 가격입니다. Int로 할지, String으로 할지는 @TaekH 님이 결정하시면 될 것 같습니다.
`menu`는 메뉴 String입니다. @Somin-DS 님께서 `split("\n")으로 배열로 만들어 쓰시면 쉬울 것 같습니다.
`date`는 다음에 말씀드릴 `MealsForDay`를 생성하기 위한 기준입니다. 맨 마지막에 어떻게 사용하실 지 한번 더 말씀드릴게요.

<br><br>

### 2. MealsForDay

같은 날짜의 Meal들이 모인 객체입니다.
@TaekH 님께서 최종적으로 7개를 만들어주셔야 하는 객체이기도 하고,
@Somin-DS 님께서 picker에 선택된 날짜에 따라서 하나씩 넘겨받은 후 적절하게 까셔서 사용하셔야 하는 객체이기도 합니다.

```swift
struct MealsForDay {
    let date: Date
    let meals: Set<Meal>
}
```

`date`는 해당하는 날짜입니다.
`meals`는 Meal들의 모임이고요. Set으로 만든 이유는 @Somin-DS 님께서 필터링 하셔서 사용하실 때 O(1)의 시간복잡도로 하실 수 있어서 입니다.

<br><br>

### 3.  Campus

단순히 Campus별로 각각 `[MealsForDay]` 을 만들어주기 위해서 필요한 객체입니다.
https://github.com/HipstuCAU/nyam_nyam/issues/2#issue-1601760761 이곳에 자세하게 설명되어있습니다.

```
enum Campus {
    case seoul
    case ansung
    
    func mealsForAllDayByCampus() -> [MealsForDay] {
        if self == .seoul {
            return []
            // getMealsForWeeks(campus: Campus) -> [MealsForDate] 가 필요합니다.
        } else {
            return []
        }
    }
}
```

<br><br>

## 해당 모델들을 이용하여 json parsing을 하실 @TaekH 님을 위한 정리

DataManager의 최종 목표는 `getMealsForWeeks(campus: Campus) -> [MealsForDate]` 을 만드는 겁니다.

1. json파일은 Seoul.json, Ansung.json 이렇게 두개가 나오는 게 맞을까요? 
2. 맨 처음 하셔야 할 일은 인자로 들어간 Campus에 따른 json 파일을 파싱하여 모두 개별 `Meal`들로 만드셔야 합니다.
3. 그리고 `Meal`의 내부 변수인 `Date`별로 분류하여 `MealsForDate`을 만드셔서 반환해야 합니다.

**Comment by TaekH** [comment]
> DataManager의 최종 목표는 getMealsForWeeks(campus: Campus) -> [MealsForDate] 을 만드는 겁니다.
>1. json파일은 Seoul.json, Ansung.json 이렇게 두개가 나오는 게 맞을까요?
>2. 맨 처음 하셔야 할 일은 인자로 들어간 Campus에 따른 json 파일을 파싱하여 모두 개별 Meal들로 만드셔야 합니다.
>3. 그리고 Meal의 내부 변수인 Date별로 분류하여 MealsForDate을 만드셔서 반환해야 합니다.

1. 먼저 json 파일은 서울 캠퍼스의 경우에는 1, 안성 캠퍼스의 경우에는 2 로 분류되어 하나의 json 파일로 나올 예정입니다.
2. 개별 Meal 을 호출할 수 있는 크롤러 또한 만들어져 있으며 전체에서 파싱또한 가능합니다.
3. Date로 분류 되어 있어 가능합니다.

**Comment by TaekH** [comment]
추후 백엔드 레포에 .json 형식과 크롤러 구현에 대한 문서를 첨부하도록 하겠습니다 !

**Comment by feldblume5263** [comment]
> 추후 백엔드 레포에 .json 형식과 크롤러 구현에 대한 문서를 첨부하도록 하겠습니다 !

넵 감사합니다!
