### ISSUE TITLE
식단의 시간 데이터를 추가합니다

### ISSUE THREAD

**Issue by TaekH** [HipstuCAU/nyam_nyam#33]
## 각 식당의 운영시간에 따라 식단마다 시간 데이터를 추가합니다.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/103012087/224341897-6e21f9c4-d4a8-45bc-9495-d454c2f25c38.png">
에서 시간 데이터를 크롤링해오기 때문에 json 형식또한

```
	"1": {
		"참슬기식당(310관 B4층)": {
			"중식(한식)": {
				"price": "4,000 원",
				"time": "11:00~13:30",
				"menu": "바지락순두부찌개|탕수만두|도시락김"
			},
			"중식(특식)": {
				"price": "5,500 원",
				"time": "11:30~13:30",
				"menu": "사천짜장덮밥|계란탕|부추잡채*꽃빵|양장피냉채|탕수만두|단무지"
			}
		},
```
time이 따로 추가될 예정입니다.

### 시간 데이터 추가에 따라 Meal 모델도 변동이 있을 예정입니다.
Meal 모델에서 기존의 MealTime이 식단의 시간으로 가고 조중석식을 MealSchedule로 변경하는 것이 나을 것 같습니다.
Meal 모델 수정에 대해서 다른 방안이 있다면 리뷰 부탁드립니다 !

**Comment by feldblume5263** [comment]
기획 상 변동사항이 생겨서
가져온 시작 시간과 끝 시간 데이터가 `Meal` 모델에 들어가야 합니다.

```swift
struct Meal: Hashable, Comparable {
    let mealTime: MealTime
    let type: MealType
    let cafeteria: Cafeteria
    let price: String
    let menu: [String]
    let date: Date
    let status: Status
    let startDate: Date // 추가 필요
    let endDate: Date // 추가 필요
}
```

의 형태로 파싱이 되어야 합니다...ㅎ

**Comment by TaekH** [comment]
> 기획 상 변동사항이 생겨서 가져온 시작 시간과 끝 시간 데이터가 `Meal` 모델에 들어가야 합니다.
> 
> ```swift
> struct Meal: Hashable, Comparable {
>     let mealTime: MealTime
>     let type: MealType
>     let cafeteria: Cafeteria
>     let price: String
>     let menu: [String]
>     let date: Date
>     let status: Status
>     let startDate: Date // 추가 필요
>     let endDate: Date // 추가 필요
> }
> ```
> 
> 의 형태로 파싱이 되어야 합니다...ㅎ

확인했습니다 !
