### ISSUE TITLE
학생식당의 ContentView UI를 수정합니다.

### ISSUE THREAD

**Issue by feldblume5263** [HipstuCAU/nyam_nyam#42]
학생식당의 경우 UI가 다르기 때문에 이를 예외처리하여 UI를 수정하려고 합니다.

![image](https://user-images.githubusercontent.com/53016167/224644740-38b7e45d-c166-4383-9208-ee25908146c0.png)

**Comment by feldblume5263** [comment]
@TaekH  테스트를 위해 기존 jsonString에 학생식당을 넣어주시면 감사하겠습니다.

**Comment by TaekH** [comment]
> @TaekH  테스트를 위해 기존 jsonString에 학생식당을 넣어주시면 감사하겠습니다.

넵! 추가하여 PR 날리겠습니다 !
