### ISSUE TITLE
AlertManager를 생성하여 사용하려고 합니다.

### ISSUE THREAD

**Issue by feldblume5263** [HipstuCAU/nyam_nyam#63]
네트워크 오류, 네트워크 지연 등 데이터를 받아오는 과정에서 Alert를 띄워줘야 할 일들이 있는데, 해당 부분을 처리하는 AlertManager를 생성하여 처리하려고 합니다.

1. Scene의 Forground -> Background 상황에서 네트워크가 연결되지 않았을 때
2. Scene의 Forground -> Background 상황에서 다운로드가 10초 이상 지연될 때
3. Scene의 Activate 상황에서 네트워크가 연결되지 않았을 때
4. Scene의 Activate 상황에서 다운로드가 10초 이상 지연될 때 

해당 조건 이외에 더 있을까요? 확인 부탁드립니다! @TaekH

**Comment by TaekH** [comment]
추가적인 부분으로 현재 따로 Alert 구현되어있는 SettingWebViewController 에서 네트워크 연결안되었을 시 나오는 Alert도 같이 들어가면 좋을 것 같아요 !

**Comment by feldblume5263** [comment]
delay 시간을 10초에서 5초로 수정합니다.
